{% set name = "CADET-Python" %}
{% set version = "1.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cadet/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0a84a4eb1e1441eb6e6c95b9aaadc018440f8e955102f6db4f495759b1ce8534

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - setuptools
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - addict
    - numpy
    - h5py
    - filelock
    - cadet >=5.0.2

test:
  imports:
    - cadet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cadet/CADET-Python
  summary: File based Python Interface for CADET
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - schmoelder
    - ronald-jaepel
